Metadata:
    type: object
    config:
        fields:
            id:
                type: 'Int!'
            firstname:
                type: 'String!'
            lastname:
                type: 'String!'
            email:
                type: 'String!'